.gitignore, src/rail/cli/commands.py, src/rail/cli/options.py, src/rail/cli/scripts.py
Translated from draft PR #43 (rail).
Now implemented as cli script.
Required for rail_attic's https://github.com/LSSTDESC/rail_attic/pull/372 (fixing goldenspike pipeline); addresses rail_attic [#356](https://github.com/LSSTDESC/rail/pull/43#356) (moving data) and rail [#26](https://github.com/LSSTDESC/rail/pull/43#26) (moving demo files).
A script to check for existence of data files and curl what is missing.
Chose not to add testing, as this could result in overuse of NERSC data storage (and testing presence of data seems to require first wiping data, which...)
Future steps could involve additional options for the command that allow the user to specify which data; perhaps utilizing the [prompting](https://click.palletsprojects.com/en/8.1.x/options/#prompting) feature in click to …
=> get data as a cli script

src/rail/estimation/algos/naive_stack.py, src/rail/estimation/algos/point_est_hist.py, src/rail/estimation/algos/random_gauss.py, src/rail/estimation/algos/train_z.py, src/rail/estimation/algos/var_inf.py, src/rail/estimation/summarizer.py, src/rail/examples_data/goldenspike_data/goldenspike.yml, src/rail/stages/__init__.py, tests/estimation/test_algos.py, tests/estimation/test_summarizers.py
This PR (and other concurrent PRs in the other repos) include renamings of modules and stages within `src/rail/estimation` for consistency and transparency to users as outlined in LSSTDESC/rail#37. (Expect a few more PRs to address the smaller set of necessary consistency/clarity changes outside `src/rail/estimation` using the same branch.) 
I request that multiple reviewers please do not hesitate to suggest changes as needed! The goals are consistency, clarity, and longevity, so if something looks unclear, inconsistent, or insufficiently flexible to accommodate future development, now is the time to make adjustments.
The following changes were made across all the rail repos, along with updates to the contributing documentation (which should be propagated to the rail python project …
=> naming consistency/clarity within src/rail/estimation

src/rail/estimation/algos/train_z.py
This is a simple one-line change where there was a hardcoded len('mag_i_lsst') to determine the number of galaxies to make duplicate trainZ distributions for.  Now we just do end-start, which in process chunk gives us that same data length.
=> change len in trainz from hardcoded value

src/rail/core/common_params.py, src/rail/estimation/estimator.py
It is not yet settled whether the default should be no calculations or all calculations done on behalf of the user. However, this PR is still mostly valid regardless of the decision. 
Introduce a new config parameters, `calculated_point_estimates`, in `SHARED_PARAMS` that will be used by subclasses of `CatEstimator`.
=> New config param to define point estimates to calculate when running a `CatEstimator` stage

src/rail/cli/commands.py, src/rail/cli/scripts.py, tests/cli/test_scripts.py
A function is added in `src/rail/cli/scripts.py` to update all the rail packages with one command.
- X I have read the Contribution Guide
- X My code follows the code style of this project
- X My code contains relevant comments and necessary documentation
=> command-update

src/rail/estimation/estimator.py, tests/estimation/test_estimator.py
This PR represents the work to move the majority of the reusable logic for calculating point estimates into the `CatEstimator` base class. This largely avoids duplicated work in the various estimator subclasses. 
When a particular estimator subclass happens to have a particularly efficient way of calculating a given point estimate, the subclass and overwrite the fine grained methods for the particular estimates. And example of this is demonstrated in the unit tests FWIW. 
One open question - would it make sense to include a call to `_calculate_point_estimates` in `_do_chunk_output`? It seems like all the subclasses make a call to that parent class method in their implementations of `_process_chunk`. If we included a call to _calculate_point_estimates there, it would save having to make …
=> Adding logic to `CatEstimator` to obey `calculated_point_estimates`.

src/rail/core/__init__.py, src/rail/core/point_estimation.py, src/rail/estimation/estimator.py, tests/core/test_point_estimation.py
This PR moved the point estimation code to a core mixin class. This will avoid duplication if/when we move to introduce a `Reducer` RAIL stage.
Additionally, we call `self.calculate_point_estimates` in `CatEstimator._do_chunk_output` to avoid having to make changes in all subclasses of CatEstimator. i.e. we get point estimation for free (when a user requests it) without having to modify any subclasses.
=> Abstract `calculate_point_estimate` up one more level

pyproject.toml, src/rail/cli/commands.py, src/rail/cli/options.py, src/rail/cli/scripts.py, tests/cli/hello_world.ipynb, tests/cli/single_number.ipynb, tests/cli/test_scripts.py
=> added skip options to rail render-nb

.github/workflows/linting.yml, .github/workflows/smoke-test.yml, .github/workflows/testing-and-coverage.yml, .pre-commit-config.yaml
Just a temporary check to ensure that out tests run on python 3.9-3.11.
=> Updating tested python versions and pre-commit hook order.

src/rail/estimation/algos/naive_stack.py, src/rail/estimation/algos/point_est_hist.py, src/rail/estimation/algos/random_gauss.py, src/rail/estimation/algos/var_inf.py, src/rail/estimation/informer.py, src/rail/estimation/summarizer.py, tests/estimation/test_algos.py, tests/estimation/test_summarizers.py
Implementing placeholders for the following dummy estimators/summarizers:
- NaiveStack
- PointEstimateHist
- RandomPZ
- VarInferenceStack
=> Implement placeholders for dummy estimators/summarizers

src/rail/estimation/algos/naive_stack.py, src/rail/estimation/algos/point_est_hist.py, src/rail/estimation/algos/var_inf.py
See isse #58 for details
Some of the dummy estimators are causing problems due to the change to the PZSummarizer base class here: https://github.com/LSSTDESC/rail_base/pull/49/files#diff-62873f07a43e74d27e697228918f71e83c43501335e3f403d24f0664ffdced74
For the summarizers that don't require a model as input, we should override the input values to be: input = [('input', QPHandle)]
The summarizers in this category are:
- PointEstHistSummarizer
- NaiveStackSummarizer
- VarInfStackSummarizer
=> Updating default inputs for estimators.

src/rail/evaluation/evaluator.py, src/rail/evaluation/metrics/cdeloss.py, src/rail/evaluation/stats_groups.py, src/rail/evaluation/utils.py
=> actually utils is unused, so remove it

src/rail/core/stage.py, tests/core/test_core.py
Add an exception when a `path` value is provided to `set_data` and it does not point to a file.
=> Raise exception when path points to non-existent file.

src/rail/core/data.py
=> patch to allow for overwriting model files

src/rail/core/stage.py, src/rail/estimation/algos/naive_stack.py, src/rail/estimation/algos/point_est_hist.py, src/rail/estimation/algos/var_inf.py, src/rail/estimation/summarizer.py
This commit parallelizes point_est_hist, and var_inf. Also I rewrote naive_stack to share functions with point_est_hist.
=> 46 parallelize var inf

src/rail/creation/degradation/quantityCut.py, src/rail/creation/degradation/spectroscopic_selections.py, src/rail/creation/degrader.py, src/rail/creation/engine.py
For LSSTDESC/rail#22 (creation docstrings only)
Made this branch before seeing Drew's dedicated branch for the issue, sorry Drew
=> Creation docstrings

src/rail/cli/scripts.py
For the bpz portion of [rail#48](https://github.com/LSSTDESC/rail/issues/48).
- I wasn't 100% sure if we wanted to keep the other (non-tar) data separate like the tar data.
- If downloading `test_dc2_training_9816_broadtypes.hdf5` and `test_dc2_train_customtemp_broadttypes.hdf5` from NERSC along with the tar works for people, here's a PR for that.
- This PR also reduces the duplicated logic across the if/else branching.
=> Add bpz files; reduce duplicated logic in if/else

src/rail/core/algo_utils.py, src/rail/core/data.py, src/rail/estimation/estimator.py, src/rail/evaluation/evaluator.py, src/rail/evaluation/metrics/pointestimates.py, src/rail/evaluation/stats_groups.py
This is work that accrues to rail issue 22 (https://github.com/LSSTDESC/rail/issues/22) 
Multiple people are contributing to this PR. Generally we've broken up the rail_base repo by top level directories. In the following list, if there's a check box, it means that the directory has already been looked over.
=> Cleaning up doc strings

src/rail/core/point_estimation.py, tests/core/test_point_estimation.py
This fixes issue #82 
Updated logic in `calculate_point_estimates` to conditionally create or append to ancil dictionary.
Prior to this change the last step in the `calculate_point_estimates` function would call `qp_ensemble.set_ancil(...)`. That function will replace any existing ancil dictionary with the new one that is passed in. 
Now, we'll check to see if the ensemble's ancil data is non-None. If so, we append the new dictionary to the existing ancil dictionary. If an ancil dictionary hasn't already been created, we'll add the new dictionary to the ensemble as the ancil dict.
=> Fix bug that overwrites ensemble ancil data in `calculate_point_estimates` method 

src/rail/estimation/algos/uniform_binning.py, src/rail/estimation/classifier.py
Brings parallelization code of UniformBinningClassifier up to parent PZClassifier. (While I'm not making the equal count classifier parallelized as well, that and future classifiers would now be able to run in parallel by implementing their own version of _process_chunk).
Adds in some docstrings to make the process as transparent as possible, and ideally a helpful template for anyone ramping up on rail-style parallelization in the future.
=> Bring parallelization up to PZClassifier

src/rail/evaluation/evaluator.py, tests/evaluation/test_evaluation.py
If the spec-z file has truth-z inside an  h5 group (for example ['photometry']['z_true']) the evaluator needs to use hdf5_groupname to access this row.
=> Added option for z_truth to be inside an hdf5 group

src/rail/creation/noisifier.py, src/rail/creation/selector.py
Changing the seed param to be a `StageParam` and setting the default to be `None`. I could be misinterpreting the way this is intended to be used, but the sense I get (and the name implies) that `seed` should be set for reproducible results in tests, but should be None when doing science.
=> Change behavior of `seed` in `Noisifier` and `Selector`

src/rail/core/data.py
=> Using the new tables_io functions for the parquet file iterator

src/rail/evaluation/evaluator.py
The line deleted will overwrite the limits set in the metric_dict to the default (0.0, 3.0). This is causing a failure in the smoke test.
=> remove the bit that overwrite limits for evaluators

src/rail/core/stage.py
This adds a check in a RailStage input_iterator if mpi is not set up.  Previously, an AttributeError would be raised [here](https://github.com/LSSTDESC/rail_base/blob/ca6cfda6a801932882e624f3f9b42d6b0c1ce11e/src/rail/core/stage.py#L352) as `self.comm` would be `None`.  Issue #116
=> Fix mpi coverage in input_iterator

pyproject.toml, src/rail/core/stage.py, src/rail/creation/degrader.py, src/rail/creation/degraders/addRandom.py, src/rail/creation/degraders/quantityCut.py, src/rail/creation/engine.py, src/rail/creation/noisifier.py, src/rail/creation/selector.py, src/rail/estimation/algos/equal_count.py, src/rail/estimation/algos/naive_stack.py, src/rail/estimation/algos/point_est_hist.py, src/rail/estimation/algos/random_gauss.py, src/rail/estimation/algos/train_z.py, src/rail/estimation/algos/true_nz.py, src/rail/estimation/algos/uniform_binning.py, src/rail/estimation/algos/var_inf.py, src/rail/estimation/classifier.py, src/rail/estimation/estimator.py, src/rail/estimation/informer.py, src/rail/estimation/summarizer.py, src/rail/evaluation/evaluator.py, src/rail/evaluation/single_evaluator.py, src/rail/tools/table_tools.py, tests/core/test_point_estimation.py
This PR updates the constructors of all stage subclasses to work with ceci version 2, in which aliases are specified in the constructor. A similar PR has been opened for each RAIL repo.
The main change is to the the constructors to accept any keywords with **kwargs and pass them to the parent class.
I have also removed any constructors which did not do anything except call the parent class constructor. Since this happens automatically if you omit the constructor, these were redundant.
Finally, in constructors I have changed I have removed hard-coded parent classes in favour of the python3 recommended super() function. If the parent class are changed in the future the constructor will still work.
=> Update for ceci version 2

pyproject.toml
Restrict numpy to <2.0.0 for now before the pandas people fix their dtype error
=> numpy<2.0.0

src/rail/cli/commands.py
I added catalog_tag as an option to the `estimate` CLI command, as well as fixed a couple linting things
=> add catalog_tag to estimate cli command addresses #148

src/rail/cli/commands.py, src/rail/cli/options.py, tests/cli/test_scripts.py
=> Added config params for estimate to cli

src/rail/estimation/estimator.py, src/rail/evaluation/evaluator.py
=> remove column that are not computed by the scipy functions

pyproject.toml
Removed the requirement for numpy version 1.
=> removed the numpy version requirement

src/rail/core/stage.py
=> remove logic for uneeded extra chunks

src/rail/estimation/algos/naive_stack.py, src/rail/estimation/algos/point_est_hist.py, src/rail/estimation/algos/true_nz.py, src/rail/estimation/algos/var_inf.py, src/rail/estimation/estimator.py
This changes the printed output of estimation stages for readability from e.g. 
```
Process 9 running estimator on chunk 53000000 - 53200000
```
to
```
Process 9 running estimator on chunk 53,000,000 - 53,200,000
```
=> Add thousands separators to progress indicator

src/rail/interfaces/pz_factory.py
trivial fix to a couple docstrings
=> fix pz factory docstring

src/rail/creation/engine.py
=> Added call to validate() in fit_model()
