src/rail/core/algo_utils.py
src/rail/stages/__init__.py

#37 
In the function `one_algo`, an optional key `is_classifier` is added to check if the tested algorithm is a classifier. If `True`, swaps `pz.estimate` to `pz.classify`.

Extend algo_utils to cover classifier

---

src/rail/estimation/estimator.py
src/rail/estimation/summarizer.py

move open_model from init to run

---

src/rail/core/data.py
tests/core/test_core.py

hook to validate date in DataHandle.set_data

---

pyproject.toml

udpated pyproject.toml

---

src/rail/core/stage.py
src/rail/core/util_stages.py

fix up logic for interactive stuff

---

src/rail/core/data.py
src/rail/core/util_stages.py

move finalize from run() to __call__() to match other Stages

---

src/rail/core/stage.py

patch to the input iterator

---

src/rail/core/stage.py

Update stage.py to close inprogress files

---

src/rail/core/stage.py

fix file closing not to overwrite files when running in chunked mode

---

src/rail/evaluation/dist_to_dist_evaluator.py
src/rail/evaluation/dist_to_point_evaluator.py
src/rail/evaluation/evaluator.py
src/rail/evaluation/point_to_point_evaluator.py
src/rail/evaluation/single_evaluator.py
src/rail/stages/__init__.py
tests/evaluation/test_evaluation.py

Change the name of base evaluator class from BaseEvaluator to Evaluator

---

src/rail/stages/__init__.py

added evaluation stage imports to rail.stages

---

src/rail/interfaces/pz_factory.py
src/rail/interfaces/tool_factory.py

Split out building stage instance in factories

---

src/rail/estimation/estimator.py

Minor improvemetns to estimators

---

src/rail/core/common_params.py
src/rail/utils/catalog_utils.py
tests/core/test_core.py

added a_env

---

src/rail/estimation/algos/naive_stack.py

Fix naive stack bootstraps

---

src/rail/core/common_params.py
src/rail/creation/degrader.py
src/rail/creation/degraders/quantityCut.py
src/rail/creation/engine.py
src/rail/estimation/algos/true_nz.py
src/rail/estimation/classifier.py
src/rail/estimation/estimator.py
src/rail/estimation/summarizer.py
src/rail/tools/table_tools.py

Switch to using Param and SHARED_PARAMS as much as possible

---

.github/workflows/smoke-test.yml
.github/workflows/testing-and-coverage.yml
pyproject.toml

test python 3.12

---

src/rail/utils/testing_utils.py

pass kwargs in testing_utils

---

src/rail/utils/catalog_utils.py

Added com_cam catalog tag

---

src/rail/evaluation/metrics/tomography.py
tests/evaluation/test_evaluation.py

Overlap evaluator based on KDE

---

src/rail/core/stage.py

Reducing the chunk size to use all the processes.

---

src/rail/core/__init__.py
src/rail/core/common_params.py
src/rail/core/introspection.py
src/rail/core/point_estimation.py
src/rail/core/stage.py
src/rail/creation/degrader.py
src/rail/creation/engine.py
src/rail/estimation/algos/random_gauss.py
src/rail/estimation/algos/train_z.py
src/rail/estimation/algos/uniform_binning.py
src/rail/estimation/classifier.py
src/rail/estimation/estimator.py
src/rail/estimation/informer.py
src/rail/estimation/summarizer.py
src/rail/evaluation/evaluator.py
src/rail/evaluation/metrics/tomography.py
src/rail/evaluation/point_to_point_evaluator.py
src/rail/pipelines/estimation/train_z_pipeline.py
src/rail/stages/__init__.py
src/rail/utils/catalog_utils.py
tests/core/test_core.py
tests/core/test_introspection.py
tests/creation/test_degraders.py
tests/evaluation/test_evaluation.py

delinting, mypy

---

src/rail/stages/__init__.py

fix imports in src/rail/stages/__init__.py

---

src/rail/estimation/informer.py

add hdf5_groupname to informer

---

src/rail/estimation/algos/point_est_hist.py

fix for issue https://github.com/LSSTDESC/rail_base/issues/204

manually del test_data in point_est_hist iterator

---

src/rail/utils/catalog_utils.py

Add euclid nir catalog tag

---

src/rail/core/enums.py
src/rail/estimation/estimator.py
tests/estimation/test_algos.py

allow for specifying distribution type
